// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/file-metadata.proto

package proto_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompressedFileMetaData struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	EncodedLen    int64                               `protobuf:"varint,1,opt,name=EncodedLen,proto3" json:"EncodedLen,omitempty"`
	PaddingSize   int32                               `protobuf:"varint,2,opt,name=PaddingSize,proto3" json:"PaddingSize,omitempty"`
	OriginalSize  int64                               `protobuf:"varint,3,opt,name=OriginalSize,proto3" json:"OriginalSize,omitempty"`
	BwtIdx        int32                               `protobuf:"varint,4,opt,name=BwtIdx,proto3" json:"BwtIdx,omitempty"`
	Frequencies   []*CompressedFileMetaData_Frequency `protobuf:"bytes,5,rep,name=Frequencies,proto3" json:"Frequencies,omitempty"`
	RleDict       []int32                             `protobuf:"varint,6,rep,packed,name=RleDict,proto3" json:"RleDict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressedFileMetaData) Reset() {
	*x = CompressedFileMetaData{}
	mi := &file_proto_file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressedFileMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressedFileMetaData) ProtoMessage() {}

func (x *CompressedFileMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressedFileMetaData.ProtoReflect.Descriptor instead.
func (*CompressedFileMetaData) Descriptor() ([]byte, []int) {
	return file_proto_file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *CompressedFileMetaData) GetEncodedLen() int64 {
	if x != nil {
		return x.EncodedLen
	}
	return 0
}

func (x *CompressedFileMetaData) GetPaddingSize() int32 {
	if x != nil {
		return x.PaddingSize
	}
	return 0
}

func (x *CompressedFileMetaData) GetOriginalSize() int64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *CompressedFileMetaData) GetBwtIdx() int32 {
	if x != nil {
		return x.BwtIdx
	}
	return 0
}

func (x *CompressedFileMetaData) GetFrequencies() []*CompressedFileMetaData_Frequency {
	if x != nil {
		return x.Frequencies
	}
	return nil
}

func (x *CompressedFileMetaData) GetRleDict() []int32 {
	if x != nil {
		return x.RleDict
	}
	return nil
}

type CompressedFileMetaData_Frequency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Char          []byte                 `protobuf:"bytes,1,opt,name=Char,proto3" json:"Char,omitempty"`
	Frequency     int32                  `protobuf:"varint,2,opt,name=Frequency,proto3" json:"Frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressedFileMetaData_Frequency) Reset() {
	*x = CompressedFileMetaData_Frequency{}
	mi := &file_proto_file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressedFileMetaData_Frequency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressedFileMetaData_Frequency) ProtoMessage() {}

func (x *CompressedFileMetaData_Frequency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressedFileMetaData_Frequency.ProtoReflect.Descriptor instead.
func (*CompressedFileMetaData_Frequency) Descriptor() ([]byte, []int) {
	return file_proto_file_metadata_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CompressedFileMetaData_Frequency) GetChar() []byte {
	if x != nil {
		return x.Char
	}
	return nil
}

func (x *CompressedFileMetaData_Frequency) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

var File_proto_file_metadata_proto protoreflect.FileDescriptor

const file_proto_file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x19proto/file-metadata.proto\x12\x05proto\"\xba\x02\n" +
	"\x16CompressedFileMetaData\x12\x1e\n" +
	"\n" +
	"EncodedLen\x18\x01 \x01(\x03R\n" +
	"EncodedLen\x12 \n" +
	"\vPaddingSize\x18\x02 \x01(\x05R\vPaddingSize\x12\"\n" +
	"\fOriginalSize\x18\x03 \x01(\x03R\fOriginalSize\x12\x16\n" +
	"\x06BwtIdx\x18\x04 \x01(\x05R\x06BwtIdx\x12I\n" +
	"\vFrequencies\x18\x05 \x03(\v2'.proto.CompressedFileMetaData.FrequencyR\vFrequencies\x12\x18\n" +
	"\aRleDict\x18\x06 \x03(\x05R\aRleDict\x1a=\n" +
	"\tFrequency\x12\x12\n" +
	"\x04Char\x18\x01 \x01(\fR\x04Char\x12\x1c\n" +
	"\tFrequency\x18\x02 \x01(\x05R\tFrequencyB\x12Z\x10proto/proto-datab\x06proto3"

var (
	file_proto_file_metadata_proto_rawDescOnce sync.Once
	file_proto_file_metadata_proto_rawDescData []byte
)

func file_proto_file_metadata_proto_rawDescGZIP() []byte {
	file_proto_file_metadata_proto_rawDescOnce.Do(func() {
		file_proto_file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_metadata_proto_rawDesc), len(file_proto_file_metadata_proto_rawDesc)))
	})
	return file_proto_file_metadata_proto_rawDescData
}

var file_proto_file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_file_metadata_proto_goTypes = []any{
	(*CompressedFileMetaData)(nil),           // 0: proto.CompressedFileMetaData
	(*CompressedFileMetaData_Frequency)(nil), // 1: proto.CompressedFileMetaData.Frequency
}
var file_proto_file_metadata_proto_depIdxs = []int32{
	1, // 0: proto.CompressedFileMetaData.Frequencies:type_name -> proto.CompressedFileMetaData.Frequency
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_file_metadata_proto_init() }
func file_proto_file_metadata_proto_init() {
	if File_proto_file_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_metadata_proto_rawDesc), len(file_proto_file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_file_metadata_proto_goTypes,
		DependencyIndexes: file_proto_file_metadata_proto_depIdxs,
		MessageInfos:      file_proto_file_metadata_proto_msgTypes,
	}.Build()
	File_proto_file_metadata_proto = out.File
	file_proto_file_metadata_proto_goTypes = nil
	file_proto_file_metadata_proto_depIdxs = nil
}
